const SUPABASE_URL='https://inuomrehmxijwvtcuxhy.supabase.co';
const ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImludW9tcmVobXhpand2dGN1eGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk3NDcwODgsImV4cCI6MjEwNTMyMzA4OH0.xHdzNWMQ7rtLgAxyOzguSHPw5Ys3GYun6rZFUKURX1E';
const API=`${SUPABASE_URL}/functions/v1/innovexa-api`;

const navItems=[['command','⌁','Command Center'],['fleet','▣','Live Fleet'],['road','◇','Road Intelligence'],['traffic','≋','Traffic Intelligence'],['incidents','⚠','Incident Center'],['evidence','◎','AI Evidence'],['analytics','⌁','Analytics'],['health','◈','Fleet Health'],['alerts','!','Alert Center'],['reports','▤','Reports'],['admin','⚙','Administration']];
const state={page:'command',data:null,selected:null,sim:true,presentation:false,role:'Control Room Operator',mapZoom:1,tick:0,filters:{severity:'ALL',type:'ALL'}};

const el=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function authHeaders(){return {'Authorization':`Bearer ${ANON_KEY}`,'apikey':ANON_KEY,'Content-Type':'application/json'}}
async function api(path,options={}){const r=await fetch(`${API}${path}`,{...options,headers:{...authHeaders(),...(options.headers||{})}});if(!r.ok)throw new Error((await r.json()).error||`API ${r.status}`);return r.json()}
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;el('toastHost').appendChild(d);setTimeout(()=>d.remove(),3200)}
function fmtTime(s){return new Date(s).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function badge(v){return `<span class="badge ${esc(v)}">${esc(v)}</span>`}
function metric(label,val,sub=''){return `<div class="metric"><span>${label}</span><strong>${val}</strong><small>${sub}</small></div>`}

function fallback(){
 const routes=['R-500D','R-335E','R-201R','R-KIAS8','R-356M','R-215H','R-290N','R-600K'];
 const buses=Array.from({length:32},(_,i)=>({id:`BUS-${String(i+1).padStart(3,'0')}`,route_id:routes[i%8],registration:`KA 01 AB ${4101+i}`,status:[9,22].includes(i+1)?'OFFLINE':'ONLINE',lat:12.91+((i*37)%95)/1000,lon:77.53+((i*53)%150)/1000,speed_kph:24+(i*7)%31,heading:(i*31)%360}));
 const types=['POTHOLE','DAMAGED_ROAD','CONGESTION','MISSING_ZEBRA_CROSSING','HIT_AND_RUN_SUSPECTED','RASH_DRIVING','WATERLOGGING','BOTTLENECK'];
 const events=Array.from({length:96},(_,i)=>({id:`EVT-DEMO-${String(i+1).padStart(4,'0')}`,event_type:['HIT_AND_RUN_SUSPECTED','RASH_DRIVING'].includes(types[i%8])?'SAFETY_INCIDENT':types[i%8].includes('CONGESTION')||types[i%8]==='BOTTLENECK'?'TRAFFIC':types[i%8].includes('POTHOLE')||types[i%8]==='DAMAGED_ROAD'?'ROAD_DEFECT':'INFRASTRUCTURE',event_subtype:types[i%8],severity:i%17===0?'CRITICAL':i%4===0?'HIGH':i%3===0?'MEDIUM':'LOW',confidence:.79+(i%19)/100,occurred_at:new Date(Date.now()-i*240000).toISOString(),lat:12.91+((i*29)%100)/1000,lon:77.53+((i*41)%160)/1000,road_name:['Outer Ring Road','Hosur Road','Old Airport Road','Bellary Road','Whitefield Main Road'][i%5],bus_id:buses[i%32].id,route_id:routes[i%8],camera_id:`CAM-FRONT-${String(i%32+1).padStart(3,'0')}`,model_name:'urban-detector',model_version:'2.4.1',review_status:'PENDING',alert_status:'NEW',plate_candidate:i%8===4?`KA 01 AB ${4500+i}`:null,anpr_confidence:i%8===4?.87:null,metadata:{simulated:true,repeat_observations:1+i%6}}));
 const devices=buses.map((b,i)=>({id:`EDGE-${String(i+1).padStart(3,'0')}`,bus_id:b.id,status:i%13===0?'STALE':i%9===0?'DEGRADED':'HEALTHY',temperature_c:49+i%12,storage_used_pct:41+(i*3)%49,network_latency_ms:38+(i*17)%150,model_version:'urban-edge-2.4.1'}));
 const alerts=events.slice(0,24).map((e,i)=>({id:`ALT-${String(i+1).padStart(4,'0')}`,event_id:e.id,category:e.event_type,severity:e.severity,title:`${e.event_subtype.replaceAll('_',' ')} requires attention`,state:i%5===0?'ASSIGNED':i%3===0?'ACKNOWLEDGED':'NEW',created_at:e.occurred_at}));
 return {routes:routes.map(id=>({id,name:id,corridor:'Bengaluru sensing corridor'})),buses,events,devices,alerts,counts:{active_buses:30,devices_online:26,events_today:events.length,critical_alerts:6,potholes:24,congestion_hotspots:18,incidents_review:10,average_confidence:88},simulated:true};
}

async function load(){try{state.data=await api('/bootstrap');toast('Live demo data connected')}catch(e){state.data=fallback();toast('Using resilient local demo data')}render();}
function renderNav(){el('nav').innerHTML=navItems.map(([id,icon,name])=>`<button class="nav-btn ${state.page===id?'active':''}" data-page="${id}"><span class="nav-icon">${icon}</span><span>${name}</span></button>`).join('');el('nav').querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render();});}
function render(){renderNav();const views={command:commandView,fleet:fleetView,road:roadView,traffic:trafficView,incidents:incidentView,evidence:evidenceView,analytics:analyticsView,health:healthView,alerts:alertsView,reports:reportsView,admin:adminView};el('view').innerHTML=views[state.page]();wirePage();el('alertCount').textContent=state.data.alerts.filter(a=>a.state==='NEW').length;}
function head(title,desc,extra=''){return `<div class="page-head"><div><div class="eyebrow">INNOVEXA / ${title}</div><h1>${title}</h1><p>${desc}</p></div><div>${extra}</div></div>`}
function commandView(){const d=state.data,c=d.counts;return head('Command Center','Fleet-wide urban intelligence synthesized in real time.',`<button class="btn primary" data-action="start-demo">Start Demo Flow</button>`)+`<div class="grid metrics">${metric('Active buses',c.active_buses,'fleet sensing now')}${metric('Edge devices online',c.devices_online,'healthy nodes')}${metric('Events detected',c.events_today,'today')}${metric('Critical alerts',c.critical_alerts,'open')}${metric('Potholes',c.potholes,'detected')}${metric('Congestion hotspots',c.congestion_hotspots,'active')}${metric('Incidents review',c.incidents_review,'pending human review')}${metric('Avg confidence',c.average_confidence+'%','AI event confidence')}</div><div class="grid command-grid"><div class="panel"><div class="panel-head"><h2>Live City Sensing Map</h2><div class="filters"><button class="chip active">Buses</button><button class="chip">Road defects</button><button class="chip">Congestion</button><button class="chip">Incidents</button></div></div>${mapMarkup()}</div><div class="panel"><div class="panel-head"><h2>Live Activity</h2><span class="eyebrow">STREAM</span></div><div class="activity">${d.events.slice(0,22).map(activityRow).join('')}</div></div></div>`}
function mapMarkup(){const d=state.data;const roads=[['12%','20%',520,12,'major'],['8%','42%',680,-8,'major congested'],['15%','66%',600,6,''],['28%','10%',500,63,''],['48%','4%',490,92,'major'],['68%','12%',420,115,''],['5%','82%',620,-28,'']];let html=`<div class="map" id="cityMap"><div class="map-grid"></div>${roads.map(r=>`<div class="road ${r[4]}" style="left:${r[0]};top:${r[1]};width:${r[2]}px;transform:rotate(${r[3]}deg)"></div>`).join('')}`;d.buses.slice(0,18).forEach((b,i)=>{const p=mapPos(b.lat,b.lon,i);html+=`<button class="marker bus" data-bus="${b.id}" style="left:${p.x}%;top:${p.y}%"><span class="dot">▣</span></button>`});d.events.filter(e=>['CRITICAL','HIGH'].includes(e.severity)).slice(0,28).forEach((e,i)=>{const p=mapPos(e.lat,e.lon,i+17);const cls=e.event_type==='SAFETY_INCIDENT'?'incident':e.event_type==='TRAFFIC'?'traffic':e.event_type==='ROAD_DEFECT'?'pothole':'infra';html+=`<button class="marker ${cls}" data-event="${e.id}" style="left:${p.x}%;top:${p.y}%"><span class="dot">${cls==='pothole'?'◇':cls==='incident'?'!':cls==='traffic'?'≈':'+'}</span></button>`});html+=`<div class="map-toolbar"><button data-map="in">+</button><button data-map="out">−</button><button data-map="reset">⌖</button></div><div class="map-legend"><span>▣ Bus</span><span>◇ Road defect</span><span>≈ Traffic</span><span>! Incident</span></div></div>`;return html}
function mapPos(lat,lon,i){const x=10+(((Number(lon)||77.59)-77.52)/.18)*80+(i%3);const y=10+(((Number(lat)||12.96)-12.90)/.12)*80+(i%4);return{x:Math.max(5,Math.min(95,x)),y:Math.max(5,Math.min(95,y))}}
function activityRow(e){return `<div class="activity-row" data-event="${e.id}"><span class="sev-dot sev-${e.severity}"></span><div><strong>${esc(e.event_subtype.replaceAll('_',' '))}</strong><p>${esc(e.road_name)} · ${esc(e.bus_id)} · ${(Number(e.confidence)*100).toFixed(0)}%</p><time>${fmtTime(e.occurred_at)}</time></div></div>`}
function fleetView(){const d=state.data;return head('Live Fleet','Moving sensing nodes, routes, device state, and camera telemetry.')+`<div class="grid two-col"><div class="panel"><div class="panel-head"><h2>Fleet Map</h2><span>${d.buses.filter(b=>b.status==='ONLINE').length}/${d.buses.length} online</span></div><div class="fleet-map">${mapMarkup()}</div></div><div class="panel"><div class="panel-head"><h2>Fleet Status</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Bus</th><th>Route</th><th>Status</th><th>Speed</th></tr></thead><tbody>${d.buses.map(b=>`<tr data-bus="${b.id}"><td>${b.id}</td><td>${b.route_id}</td><td>${badge(b.status)}</td><td>${b.speed_kph} km/h</td></tr>`).join('')}</tbody></table></div></div></div><div class="panel" style="margin-top:12px"><div class="panel-head"><h2>Simulated Camera Feeds · BUS-001</h2><span class="eyebrow">AI OVERLAY</span></div><div class="grid camera-grid">${['Front','Rear','Left','Right','Cabin'].map((n,i)=>`<div class="camera"><span class="cam-label">${n}</span>${i<4?`<span class="bbox" data-label="${i===0?'CAR 97%':i===1?'PEDESTRIAN 94%':'VEHICLE 91%'}"></span>`:''}</div>`).join('')}</div></div>`}
function roadView(){const rows=state.data.events.filter(e=>e.event_type==='ROAD_DEFECT'||e.event_type==='INFRASTRUCTURE');return head('Road Intelligence','Persistent road defects and infrastructure deficiencies by segment.')+`<div class="grid three-col" style="margin-bottom:12px">${metric('Open road issues',rows.length)}${metric('Critical',rows.filter(x=>x.severity==='CRITICAL').length)}${metric('Repeat observations',rows.reduce((s,x)=>s+(x.metadata?.repeat_observations||1),0))}</div>${eventTable(rows)}`}
function trafficView(){const rows=state.data.events.filter(e=>e.event_type==='TRAFFIC');return head('Traffic Intelligence','Congestion, bottlenecks, route delays and density trends.')+`<div class="grid three-col" style="margin-bottom:12px">${metric('Traffic events',rows.length)}${metric('Average corridor speed','28 km/h')}${metric('Peak route delay','17 min')}</div><div class="grid two-col"><div class="panel chart"><div class="panel-head"><h2>Traffic density by hour</h2></div><div class="bars">${[28,34,45,66,88,95,83,71,58,64,80,91,76,60].map((v,i)=>`<div class="bar ${v>80?'hot':''}" style="height:${v}%"><span>${6+i}</span></div>`).join('')}</div></div><div class="panel chart"><div class="panel-head"><h2>Vehicle class composition</h2></div><div class="donut"></div></div></div><div style="margin-top:12px">${eventTable(rows)}</div>`}
function incidentView(){const rows=state.data.events.filter(e=>e.event_type==='SAFETY_INCIDENT');return head('Incident Center','Human-in-the-loop investigation of safety-critical events.')+`<div class="grid three-col" style="margin-bottom:12px">${metric('Open incidents',rows.length)}${metric('ANPR candidates',rows.filter(x=>x.plate_candidate).length)}${metric('Pending human review',rows.filter(x=>x.review_status==='PENDING').length)}</div>${eventTable(rows)}`}
function evidenceView(){const rows=state.data.events.slice(0,40);return head('AI Evidence','Searchable evidence library with AI overlays and validation status.')+`<div class="grid three-col">${rows.slice(0,18).map(e=>`<div class="panel" data-event="${e.id}" style="cursor:pointer"><div class="evidence"><span class="bbox" data-label="${e.event_subtype.replaceAll('_',' ')} ${(e.confidence*100).toFixed(0)}%"></span></div><div style="padding:10px"><strong>${e.id}</strong><p style="font-size:10px;color:var(--muted)">${e.road_name} · ${e.bus_id}</p>${badge(e.review_status)}</div></div>`).join('')}</div>`}
function analyticsView(){const d=state.data;return head('Analytics','Road health, traffic, coverage and infrastructure trends.')+`<div class="grid three-col">${metric('Road condition score','74 / 100')}${metric('Unique km observed','1,842 km')}${metric('City sensing coverage','78%')}${metric('Persistent hotspots','31')}${metric('Avg route delay','6.8 min')}${metric('Sensing frequency','4.7 passes/hr')}</div><div class="grid two-col" style="margin-top:12px"><div class="panel chart"><div class="panel-head"><h2>Defect severity trend</h2></div><div class="bars">${[33,40,47,52,61,57,68,72,67,75,71,66].map((v,i)=>`<div class="bar" style="height:${v}%"><span>W${i+1}</span></div>`).join('')}</div></div><div class="panel chart"><div class="panel-head"><h2>Sensing coverage by route</h2></div><div class="bars">${d.routes.map((r,i)=>`<div class="bar" style="height:${55+(i*7)%42}%"><span>${r.id.replace('R-','')}</span></div>`).join('')}</div></div></div>`}
function healthView(){const d=state.data;return head('Fleet Health','Edge devices, cameras, GPS, network and storage health.')+`<div class="grid three-col" style="margin-bottom:12px">${metric('Healthy',d.devices.filter(x=>x.status==='HEALTHY').length)}${metric('Degraded',d.devices.filter(x=>x.status==='DEGRADED').length)}${metric('Stale / Offline',d.devices.filter(x=>['STALE','OFFLINE'].includes(x.status)).length)}</div><div class="panel table-wrap"><table class="data-table"><thead><tr><th>Device</th><th>Bus</th><th>Status</th><th>Temp</th><th>Storage</th><th>Latency</th><th>Model</th></tr></thead><tbody>${d.devices.map(x=>`<tr><td>${x.id}</td><td>${x.bus_id}</td><td>${badge(x.status)}</td><td>${x.temperature_c}°C</td><td>${x.storage_used_pct}%</td><td>${x.network_latency_ms}ms</td><td>${x.model_version}</td></tr>`).join('')}</tbody></table></div>`}
function alertsView(){const d=state.data;return head('Alert Center','Operational alert workflow: New → Acknowledged → Assigned → Resolved.')+`<div class="panel table-wrap"><table class="data-table"><thead><tr><th>Alert</th><th>Category</th><th>Severity</th><th>Title</th><th>State</th><th>Action</th></tr></thead><tbody>${d.alerts.map(a=>`<tr><td>${a.id}</td><td>${a.category}</td><td>${badge(a.severity)}</td><td>${a.title}</td><td>${badge(a.state)}</td><td>${alertAction(a)}</td></tr>`).join('')}</tbody></table></div>`}
function alertAction(a){const next=a.state==='NEW'?'ACKNOWLEDGED':a.state==='ACKNOWLEDGED'?'ASSIGNED':a.state==='ASSIGNED'?'RESOLVED':'RESOLVED';return `<button class="btn" data-alert="${a.id}" data-next="${next}">${next}</button>`}
function reportsView(){return head('Reports','Build and export operational intelligence reports.')+`<div class="panel report-builder"><div class="form-row"><div class="field"><label>Report type</label><select><option>Road condition report</option><option>Infrastructure deficiency</option><option>Congestion report</option><option>Incident report</option><option>Fleet health report</option></select></div><div class="field"><label>Date range</label><input value="Today"></div><div class="field"><label>Zone</label><select><option>All Bengaluru demo zones</option></select></div><div class="field"><label>Route</label><select><option>All routes</option></select></div></div><div class="actions"><button class="btn primary" data-export="csv">Export CSV</button><button class="btn" data-export="json">Export JSON</button><button class="btn" onclick="window.print()">Printable view</button></div></div>`}
function adminView(){const roles=['System Administrator','Control Room Operator','Road/Civic Officer','Traffic/Police Reviewer','Urban Planner / Analyst'];return head('Administration','Prototype role simulation and system registry.')+`<div class="grid two-col"><div class="panel"><div class="panel-head"><h2>Role Simulation</h2><span>Current: ${state.role}</span></div><div style="padding:12px">${roles.map(r=>`<button class="role-option" data-role="${r}">${r}</button>`).join('')}</div></div><div class="panel"><div class="panel-head"><h2>System Inventory</h2></div><div style="padding:12px">${metric('Users','18')}${metric('Buses',state.data.buses.length)}${metric('Edge devices',state.data.devices.length)}${metric('AI models','4')}</div></div></div>`}
function eventTable(rows){return `<div class="panel table-wrap"><table class="data-table"><thead><tr><th>Event</th><th>Type</th><th>Road</th><th>Severity</th><th>Confidence</th><th>Bus</th><th>Review</th></tr></thead><tbody>${rows.map(e=>`<tr data-event="${e.id}"><td>${e.id}</td><td>${e.event_subtype.replaceAll('_',' ')}</td><td>${e.road_name}</td><td>${badge(e.severity)}</td><td>${(e.confidence*100).toFixed(0)}%</td><td>${e.bus_id}</td><td>${badge(e.review_status)}</td></tr>`).join('')}</tbody></table></div>`}
function wirePage(){document.querySelectorAll('[data-event]').forEach(x=>x.onclick=()=>openEvent(x.dataset.event));document.querySelectorAll('[data-bus]').forEach(x=>x.onclick=()=>openBus(x.dataset.bus));document.querySelectorAll('[data-map]').forEach(x=>x.onclick=()=>{state.mapZoom=x.dataset.map==='reset'?1:Math.max(.8,Math.min(1.5,state.mapZoom+(x.dataset.map==='in'?.1:-.1)));const m=el('cityMap');if(m)m.style.transform=`scale(${state.mapZoom})`;});document.querySelectorAll('[data-alert]').forEach(b=>b.onclick=()=>updateAlert(b.dataset.alert,b.dataset.next));document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportReport(b.dataset.export));document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{state.role=b.dataset.role;toast(`Role switched to ${state.role}`);render()});const sd=document.querySelector('[data-action="start-demo"]');if(sd)sd.onclick=startDemoFlow;}
function openEvent(id){const e=state.data.events.find(x=>x.id===id);if(!e)return;state.selected=e;el('drawer').innerHTML=`<div class="drawer-head"><div><div class="eyebrow">EVENT INTELLIGENCE</div><strong>${e.id}</strong></div><button class="drawer-close" id="closeDrawer">×</button></div><div class="drawer-body"><div class="evidence"><span class="bbox" data-label="${e.event_subtype.replaceAll('_',' ')} ${(Number(e.confidence)*100).toFixed(0)}%"></span></div><dl class="kv"><dt>Type</dt><dd>${e.event_type}</dd><dt>Subtype</dt><dd>${e.event_subtype}</dd><dt>Severity</dt><dd>${e.severity}</dd><dt>AI confidence</dt><dd>${(Number(e.confidence)*100).toFixed(1)}%</dd><dt>Timestamp</dt><dd>${new Date(e.occurred_at).toLocaleString()}</dd><dt>Coordinates</dt><dd>${Number(e.lat).toFixed(5)}, ${Number(e.lon).toFixed(5)}</dd><dt>Bus / Route</dt><dd>${e.bus_id} / ${e.route_id}</dd><dt>Camera</dt><dd>${e.camera_id}</dd><dt>Model</dt><dd>${e.model_name} ${e.model_version}</dd><dt>Review</dt><dd>${e.review_status}</dd><dt>Alert</dt><dd>${e.alert_status}</dd>${e.plate_candidate?`<dt>ANPR candidate</dt><dd>${e.plate_candidate} (${(Number(e.anpr_confidence)*100).toFixed(0)}%)</dd>`:''}</dl>${e.plate_candidate?`<p style="font-size:10px;color:var(--amber)">AI-generated plate candidate requiring human verification. It does not establish identity or guilt.</p>`:''}<div class="actions"><button class="btn primary" data-review="VERIFIED">Verify</button><button class="btn danger" data-review="REJECTED">Reject false positive</button><button class="btn" data-review="UNCERTAIN">Mark uncertain</button><button class="btn" data-evt-alert="ACKNOWLEDGED">Acknowledge</button><button class="btn" data-evt-alert="ASSIGNED">Assign</button><button class="btn">Generate incident report</button></div></div>`;el('drawer').classList.add('open');el('drawer').setAttribute('aria-hidden','false');el('closeDrawer').onclick=closeDrawer;el('drawer').querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>updateEvent(e.id,{review_status:b.dataset.review}));el('drawer').querySelectorAll('[data-evt-alert]').forEach(b=>b.onclick=()=>updateEvent(e.id,{alert_status:b.dataset.evtAlert}));}
function closeDrawer(){el('drawer').classList.remove('open');el('drawer').setAttribute('aria-hidden','true')}
function openBus(id){const b=state.data.buses.find(x=>x.id===id),d=state.data.devices.find(x=>x.bus_id===id);if(!b)return;el('drawer').innerHTML=`<div class="drawer-head"><div><div class="eyebrow">MOBILE SENSING NODE</div><strong>${b.id}</strong></div><button class="drawer-close" id="closeDrawer">×</button></div><div class="drawer-body"><dl class="kv"><dt>Registration</dt><dd>${b.registration}</dd><dt>Route</dt><dd>${b.route_id}</dd><dt>Status</dt><dd>${b.status}</dd><dt>Speed</dt><dd>${b.speed_kph} km/h</dd><dt>Heading</dt><dd>${b.heading}°</dd><dt>GPS</dt><dd>${Number(b.lat).toFixed(5)}, ${Number(b.lon).toFixed(5)}</dd><dt>Edge device</dt><dd>${d?.id||'—'} / ${d?.status||'—'}</dd><dt>Network</dt><dd>${d?.network_latency_ms||'—'} ms</dd><dt>Storage</dt><dd>${d?.storage_used_pct||'—'}%</dd><dt>Model</dt><dd>${d?.model_version||'—'}</dd></dl><div class="camera"><span class="cam-label">Front camera</span><span class="bbox" data-label="CAR 97%"></span></div></div>`;el('drawer').classList.add('open');el('closeDrawer').onclick=closeDrawer;}
async function updateEvent(id,patch){const e=state.data.events.find(x=>x.id===id);Object.assign(e,patch);render();openEvent(id);try{await api(`/events/${id}`,{method:'PATCH',body:JSON.stringify(patch)});toast(`Event ${id} updated`)}catch{toast('Prototype state updated locally; remote write unavailable')}}
async function updateAlert(id,next){const a=state.data.alerts.find(x=>x.id===id);if(next==='RESOLVED'&&a.state==='RESOLVED'){toast('Alert already resolved');return}a.state=next;if(next==='ASSIGNED')a.assigned_to='Control Room A';render();try{await api(`/alerts/${id}`,{method:'PATCH',body:JSON.stringify({state:next,assigned_to:a.assigned_to})});toast(`Alert ${id} → ${next}`)}catch{toast('Alert updated locally')}}
function exportReport(type){const rows=state.data.events;let content,mime,name;if(type==='json'){content=JSON.stringify({generated_at:new Date().toISOString(),simulated:true,events:rows},null,2);mime='application/json';name='innovexa-report.json'}else{const cols=['id','event_type','event_subtype','severity','confidence','occurred_at','road_name','bus_id','route_id','review_status'];content=[cols.join(','),...rows.map(r=>cols.map(c=>`"${String(r[c]??'').replaceAll('"','""')}"`).join(','))].join('\n');mime='text/csv';name='innovexa-report.csv'}const blob=new Blob([content],{type:mime}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href);toast(`${type.toUpperCase()} report exported`)}
function startDemoFlow(){toast('Demo: BUS-014 detected a new pothole on Outer Ring Road');setTimeout(()=>{const e=state.data.events.find(x=>x.event_subtype==='POTHOLE');if(e)openEvent(e.id)},700)}
function openPalette(){el('palette').classList.remove('hidden');el('paletteInput').value='';renderPalette('');setTimeout(()=>el('paletteInput').focus(),0)}
function renderPalette(q){q=q.toLowerCase();const commands=[...navItems.map(([id,,name])=>({label:`Go to ${name}`,kind:'page',id})),{label:'Show critical alerts',kind:'page',id:'alerts'},{label:'Show potholes',kind:'search',id:'POTHOLE'},{label:'Show offline devices',kind:'page',id:'health'}];const entities=[...state.data.events.slice(0,50).map(e=>({label:`${e.id} · ${e.event_subtype} · ${e.road_name}`,kind:'event',id:e.id})),...state.data.buses.map(b=>({label:`${b.id} · ${b.registration} · ${b.route_id}`,kind:'bus',id:b.id}))];const arr=[...commands,...entities].filter(x=>x.label.toLowerCase().includes(q)).slice(0,12);el('paletteResults').innerHTML=arr.map((x,i)=>`<div class="palette-result" data-kind="${x.kind}" data-id="${x.id}"><span>${x.label}</span><span>↵</span></div>`).join('');el('paletteResults').querySelectorAll('.palette-result').forEach(x=>x.onclick=()=>{el('palette').classList.add('hidden');if(x.dataset.kind==='page'){state.page=x.dataset.id;render()}if(x.dataset.kind==='event')openEvent(x.dataset.id);if(x.dataset.kind==='bus')openBus(x.dataset.id);if(x.dataset.kind==='search'){state.page='road';render();toast(`Filtered to ${x.dataset.id}`)}})}
function roleModal(){el('modal').classList.remove('hidden');const roles=['System Administrator','Control Room Operator','Road/Civic Officer','Traffic/Police Reviewer','Urban Planner / Analyst'];el('modal').innerHTML=`<div class="role-menu"><div class="eyebrow">ROLE SIMULATION</div><h3>Active role</h3>${roles.map(r=>`<button class="role-option" data-modal-role="${r}">${r}${r===state.role?' ✓':''}</button>`).join('')}<button class="btn" id="closeModal" style="margin-top:12px">Close</button></div>`;el('closeModal').onclick=()=>el('modal').classList.add('hidden');el('modal').querySelectorAll('[data-modal-role]').forEach(b=>b.onclick=()=>{state.role=b.dataset.modalRole;el('roleButton').textContent=state.role.split(' ').map(x=>x[0]).join('').slice(0,2);el('modal').classList.add('hidden');toast(`Role: ${state.role}`);render()})}
function tick(){el('clock').textContent=new Date().toLocaleString('en-IN',{hour12:false});if(state.sim&&state.data){state.tick++;state.data.buses.forEach((b,i)=>{if(b.status!=='OFFLINE'){b.lat=Number(b.lat)+Math.sin((state.tick+i)/7)*.00003;b.lon=Number(b.lon)+Math.cos((state.tick+i)/8)*.00003}});if(state.tick%15===0){const online=state.data.devices.find(d=>d.status==='STALE');if(online){online.status='HEALTHY';toast(`${online.id} heartbeat recovered`)}}if(state.page==='command'&&state.tick%3===0)render();}}

el('searchTrigger').onclick=openPalette;el('paletteInput').oninput=e=>renderPalette(e.target.value);el('palette').onclick=e=>{if(e.target===el('palette'))el('palette').classList.add('hidden')};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}if(e.key==='Escape'){el('palette').classList.add('hidden');closeDrawer()}});el('simToggle').onclick=()=>{state.sim=!state.sim;el('simToggle').textContent=state.sim?'Ⅱ':'▶';toast(state.sim?'Simulation resumed':'Simulation paused')};el('presentationToggle').onclick=()=>{state.presentation=!state.presentation;document.body.classList.toggle('presentation',state.presentation);toast(state.presentation?'Presentation mode enabled':'Presentation mode disabled')};el('collapseNav').onclick=()=>el('sidebar').classList.toggle('collapsed');el('roleButton').onclick=roleModal;el('alertBell').onclick=()=>{state.page='alerts';render()};setInterval(tick,1000);tick();load();
